Updates after first tests

diff --git a/config/functions/config_voms_admin_oracle b/config/functions/config_voms_admin_oracle
--- a/config/functions/config_voms_admin_oracle
+++ b/config/functions/config_voms_admin_oracle
@@ -31,15 +31,10 @@
 
 config_voms_admin_oracle_check () {
 
-requires $1 VOS VO__VOMS_ADMIN_PORT VO__VOMS_ADMIN_DB_NAME VO__VOMS_ADMIN_DB_USER \ 
-            VO__VOMS_ADMIN_DB_USER_PASSWORD VOMS_ADMIN_ORACLE_CLIENT
+# The following variables are declared always per VO
+requires $1 VOS VO__VOMS_ADMIN_DB_NAME VO__VOMS_ADMIN_DB_USER VO__VOMS_ADMIN_DB_USER_PASSWORD VO__VOMS_ADMIN_PORT
 
-if [ ! "VOMS_ADMIN_HOSTNAME" ]; then 
-  requires $1 VO__VOMS_ADMIN_HOSTNAME 
-fi
-if [ ! "VOMS_ADMIN_CERT" ]; then 
-  requires $1 VO__VOMS_ADMIN_CERT 
-fi
+# The following variables can be defined per VOMS server or per VO
 if [ ! "VOMS_ADMIN_DB_HOST" ]; then 
   requires $1 VO__VOMS_ADMIN_DB_HOST 
 fi
@@ -49,9 +44,12 @@ fi
 if [ ! "VOMS_ADMIN_MAIL" ]; then 
   requires $1 VO__VOMS_ADMIN_MAIL 
 fi
-if [ ! "VOMS_ADMIN_ORACLE_CONNECTION_STRING" ]; then 
-  requires $1 VO__VOMS_ADMIN_ORACLE_CONNECTION_STRING 
+if [ ! "VOMS_ADMIN_CERT" ]; then
+  requires $1 VO__VOMS_ADMIN_CERT
 fi
+
+# The following variables are declared by default but we check them too
+requires $1 VOMS_ADMIN_ORACLE_CLIENT VOMS_ADMIN_INSTALL
 }
 
 config_voms_admin_oracle_setenv () {
@@ -72,6 +70,9 @@ fi
 yaimgridenv_set TNS_ADMIN ${GLITE_LOCATION}/etc/voms
 yaimgridenv_set GLITE_LOCATION_LOG ${GLITE_LOCATION_LOG}
 yaimgridenv_set GLITE_LOCATION_TMP ${GLITE_LOCATION_TMP}
+yaimgridenv_set VOMSORACLE_MIN_CONNECTION ${VOMS_ADMIN_ORACLE_MIN_CONNECTIONS}
+yaimgridenv_set VOMSORACLE_MAX_CONNECTION ${VOMS_ADMIN_ORACLE_MAX_CONNECTIONS}
+yaimgridenv_set VOMSORACLE_INC_CONNECTION ${VOMS_ADMIN_ORACLE_START_CONNECTIONS}
 
 }
 
@@ -86,81 +87,178 @@ for vo in ${VOS}; do
   yaimlog DEBUG "Configure mandatory parameters"
 
   VO=`echo ${vo} | sed -e 's/-/_/g' -e 's/\./_/g' | tr '[:lower:]' '[:upper:]'`
-  vars="VOMS_ADMIN_HOSTNAME VOMS_ADMIN_CERT VOMS_ADMIN_DB_HOST VOMS_ADMIN_SMTP_HOST VOMS_ADMIN_MAIL VOMS_ADMIN_ORACLE_PORT VOMS_ADMIN_DEPLOY_DATABASE        VOMS_ADMIN_WEB_REGISTRATION VOMS_ADMIN_REQUEST_SCHEDULER VOMS_ADMIN_ORACLE_CONNECTION_STRING"
-  yaimlog DEBUG "Processing variables ${vars}"
+
+  command=" --vo ${vo} --dbtype "oracle""
+
+  vars="VOMS_ADMIN_DB_NAME 
+        VOMS_ADMIN_DB_USER 
+        VOMS_ADMIN_DB_USER_PASSWORD 
+        VOMS_ADMIN_DB_HOST 
+        VOMS_ADMIN_ORACLE_PORT 
+        VOMS_ADMIN_PORT 
+        VOMS_ADMIN_SMTP_HOST 
+        VOMS_ADMIN_MAIL 
+        VOMS_ADMIN_CERT"
+
+  options=(dbname 
+           dbusername 
+           dbpassword 
+           dbhost 
+           dbport 
+           port 
+           smtp-host 
+           mail-from admincert)
+
+  yaimlog DEBUG "Building up the command"
+  j=0
   for i in ${vars}; do
-    yaimlog DEBUG "Processing variable $i..."
     value=`get_vo_param ${vo} $i`
     if [ "x${value}" != "x" ]; then
-      VAR_$i=$value
+      command="$command --${options[$j]} $value"
     else
-      VAR_$i=`eval echo "\\$$i"`
+      command="$command --${options[$j]} ${!i}"
     fi
-    yaimlog DEBUG "VAR_$i is `eval echo "\\$VAR_$i"`"
+    j=`expr $j + 1`
   done
- 
-  options=" --vo ${vo} \
-            --dbtype "oracle" \
-            --dbname `eval echo "\\$VO_${VO}_VOMS_ADMIN_DB_NAME"` \
-            --dbusername `eval echo "\\$VO_${VO}_VOMS_ADMIN_DB_USER"` \
-            --dbpassword `eval echo "\\$VO_${VO}_VOMS_ADMIN_DB_USER_PASSWORD"` \
-            --dbhost ${VAR_VOMS_ADMIN_DB_HOST} \
-            --dbport ${VAR_VOMS_ADMIN_ORACLE_PORT} \
-            --port `eval echo "\\$VO_${VO}_VOMS_ADMIN_PORT"` \
-            --smtp-host ${VAR_VOMS_ADMIN_SMTP_HOST}\
-            --mail-from ${VAR_VOMS_ADMIN_MAIL} \
-            --admincert ${VAR_VOMS_ADMIN_CERT}"
-
+  
   yaimlog DEBUG "Configure optional parameters"
-            
-  if [ "x${VAR_VOMS_ADMIN_DEPLOY_DATABASE}" == "xno" ]; then
-    options=echo "${options} --skip-database"
+ 
+  value=`get_vo_param ${vo} VOMS_ADMIN_DEPLOY_DATABASE`
+  if [ "x${value}" == "xno" ]; then 
+    command="$command --skip-database"
   else
-    options=echo "${options} --deploy-database"
+    if [ "x${value}" == "xyes" ]; then
+      command="${command} --deploy-database"
+    else 
+      if [ "x${VOMS_ADMIN_DEPLOY_DATABASE}" == "xno" ]; then
+        command="${command} --skip-database"
+      else
+        if [ "x${VOMS_ADMIN_DEPLOY_DATABASE}" == "xyes" ]; then
+          command="${command} --deploy-database"
+        else
+           command="${command} --skip-database"
+        fi
+      fi
+    fi
   fi
 
-  if [ "x${VAR_VOMS_ADMIN_WEB_REGISTRATION}" == "xyes" ]; then
-    options=echo "${options} --disable-webui-requests"
+  value=`get_vo_param ${vo} VOMS_ADMIN_WEB_REGISTRATION`
+  if [ "x${value}" == "xyes" ]; then
+    command="${command} --disable-webui-requests"
+  else
+    if [ "x${VOMS_ADMIN_WEB_REGISTRATION}" == "xyes" ]; then
+      command="${command} --disable-webui-requests"
+    fi
   fi 
 
   if [ "x${VOMS_ADMIN_VERBOSE}" == "xyes" ]; then
-    options=echo "${options} --verbose"
+    command="${command} --verbose"
   fi
 
   if [ -n "${VOMS_ADMIN_TOMCAT_GROUP}" ]; then
-    options=echo "${options} --tomcat-group ${VOMS_ADMIN_TOMCAT_GROUP}"
+    command="${command} --tomcat-group ${VOMS_ADMIN_TOMCAT_GROUP}"
   fi
 
   if [ -n "${VOMS_ADMIN_VOMS_GROUP}" ]; then
-    options=echo "${options} --voms-group ${VOMS_ADMIN_VOMS_GROUP}"
+    command="${command} --voms-group ${VOMS_ADMIN_VOMS_GROUP}"
   fi
 
-  if [ -n "${VAR_VOMS_ADMIN_ORACLE_CONNECTION_STRING}" ]; then
-    options=echo "${options} --oracle-conn-string ${VAR_VOMS_ADMIN_ORACLE_CONNECTION_STRING}"
+  if [ -f $GLITE_LOCATION/etc/voms/tnsnames.ora ]; then
+    rm -rf $GLITE_LOCATION/etc/voms/tnsnames.ora
+  fi
+  value=`get_vo_param ${vo} VOMS_ADMIN_ORACLE_CONNECTION_STRING`
+  if [ -n "${value}" ]; then
+    oci=${value}
     yaimlog DEBUG "Create the tnsnames.ora file"
-    echo "${VAR_VOMS_ADMIN_ORACLE_CONNECTION_STRING}" >> $GLITE_LOCATION/etc/voms/tnsnames.ora
+    echo "${value}" >> $GLITE_LOCATION/etc/voms/tnsnames.ora
+  else
+    if [ -n "${VOMS_ADMIN_ORACLE_CONNECTION_STRING}" ]; then
+      oci=${VOMS_ADMIN_ORACLE_CONNECTION_STRING}
+      yaimlog DEBUG "Create the tnsnames.ora file"
+      echo "${VOMS_ADMIN_ORACLE_CONNECTION_STRING}" >> $GLITE_LOCATION/etc/voms/tnsnames.ora
+    else
+      oci=""
+    fi
   fi
 
-  yaimlog DEBUG "The options of the command are ${options}"  
+  yaimlog DEBUG "The command is ${command}"  
   yaimlog DEBUG "Configure voms-admin"
-  ${GLITE_LOCATION}/sbin/voms-admin-configure install ${options}
+  ${GLITE_LOCATION}/sbin/voms-admin-configure install ${command}
 
   yaimlog DEBUG "Configure OCI support"
-  if [ -n "${VAR_VOMS_ADMIN_VOMS_GROUP}" ]; then
+  if [ -n "${oci}" ]; then
     mv ${GLITE_LOCATION_VAR}/etc/voms-admin/${vo}/voms.database.properties ${GLITE_LOCATION_VAR}/etc/voms-admin/${vo}/voms.database.properties.old
     cat ${GLITE_LOCATION_VAR}/etc/voms-admin/${vo}/voms.database.properties.old sed \
-	-e "s#^jdbc.URL .*#jdbc.URL jdbc:oracle:oci:`echo -e \"${VAR_VOMS_ADMIN_ORACLE_CONNECTION_STRING}\"`#" \
+	-e "s#^jdbc.URL .*#jdbc.URL jdbc:oracle:oci:`echo -e \"${oci}\"`#" \
         > ${GLITE_LOCATION_VAR}/etc/voms-admin/${vo}/voms.database.properties
   fi
 
   yaimlog DEBUG "Setting OCI support for tomcat"
-  echo "JAVA_OPTS="-Djava.library.path=${VOMS_ADMIN_ORACLE_CLIENT}/lib" >> ${CATALINA_HOME}/conf/tomcat5.conf
-  echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/${VOMS_ADMIN_ORACLE_CLIENT}" >> ${CATALINA_HOME}/conf/tomcat5.conf
-  echo "export TNS_ADMIN="${GLITE_LOCATION}/etc/voms" >> ${CATALINA_HOME}/conf/tomcat5.conf
-  cp ${VOMS_ADMIN_ORACLE_CLIENT}/lib/ojdbc14.jar ${CATALINA_HOME}/common/lib/.
+  if grep -q "^JAVA_OPTS" ${CATALINA_HOME}/conf/tomcat5.conf; then
+    mv ${CATALINA_HOME}/conf/tomcat5.conf ${CATALINA_HOME}/conf/tomcat5.conf.old
+    cat ${CATALINA_HOME}/conf/tomcat5.conf.old | sed -e "s#^JAVA_OPTS .*#JAVA_OPTS=\"$JAVA_OPTS -Djava.library.path=${VOMS_ADMIN_ORACLE_CLIENT}/lib\"#" \
+    > ${CATALINA_HOME}/conf/tomcat5.conf
+  else
+    echo "JAVA_OPTS=\"$JAVA_OPTS -Djava.library.path=${VOMS_ADMIN_ORACLE_CLIENT}/lib\"" >> ${CATALINA_HOME}/conf/tomcat5.conf
+  fi
+
+  if grep -q "^export LD_LIBRARY_PATH" ${CATALINA_HOME}/conf/tomcat5.conf; then
+    mv ${CATALINA_HOME}/conf/tomcat5.conf ${CATALINA_HOME}/conf/tomcat5.conf.old
+    cat ${CATALINA_HOME}/conf/tomcat5.conf.old | sed -e "s#^export LD_LIBRARY_PATH .*#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${VOMS_ADMIN_ORACLE_CLIENT}#" \
+    > ${CATALINA_HOME}/conf/tomcat5.conf
+  else
+    echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${VOMS_ADMIN_ORACLE_CLIENT}" >> ${CATALINA_HOME}/conf/tomcat5.conf
+  fi
+
+  if grep -q "^export TNS_ADMIN" ${CATALINA_HOME}/conf/tomcat5.conf; then
+    mv ${CATALINA_HOME}/conf/tomcat5.conf ${CATALINA_HOME}/conf/tomcat5.conf.old
+    cat ${CATALINA_HOME}/conf/tomcat5.conf.old | sed -e "s#^export TNS_ADMIN .*#export TNS_ADMIN=\"${GLITE_LOCATION}/etc/voms\"#" \
+    > ${CATALINA_HOME}/conf/tomcat5.conf
+  else
+    echo "export TNS_ADMIN=\"${GLITE_LOCATION}/etc/voms\"" >> ${CATALINA_HOME}/conf/tomcat5.conf
+  fi
+  
+  if [ -f ${VOMS_ADMIN_ORACLE_CLIENT}/lib/ojdbc14.jar ]; then
+    cp ${VOMS_ADMIN_ORACLE_CLIENT}/lib/ojdbc14.jar ${CATALINA_HOME}/common/lib/.
+  else
+    yaimlog ERROR "${VOMS_ADMIN_ORACLE_CLIENT}/lib/ojdbc14.jar doesn't exist and it's needed to configure the OCI support in Tomcat"
+    yestr ${YEX_NOSUCHFILE}
+    yaimlog ERROR "${YERRORSTR}"
+    exit ${YEX_NOSUCHFILE}
+  fi
+
+  yaimlog DEBUG "Configure Tomcat memory size"
+  MemSize=`free -m | awk '/^Mem/{if($2 <= 4096) printf "%i", $2/2; else print "2048";}'`
+  MemSize=${MemSize:-256}
+  CATALINA_OPTS="-Xmx${MemSize}M -server -Dsun.net.client.defaultReadTimeout=240000 -XX:MaxPermSize=256m"
+  if grep -q "^CATALINA_OPTS" ${CATALINA_HOME}/conf/tomcat5.conf; then
+    mv ${CATALINA_HOME}/conf/tomcat5.conf ${CATALINA_HOME}/conf/tomcat5.conf.old
+    cat ${CATALINA_HOME}/conf/tomcat5.conf.old | sed -e "s#^CATALINA_OPTS=.*#CATALINA_OPTS=\"${CATALINA_OPTS}\"#" \
+    > ${CATALINA_HOME}/conf/tomcat5.conf
+  else
+    echo "CATALINA_OPTS=\"${CATALINA_OPTS}\"" >> ${CATALINA_HOME}/conf/tomcat5.conf
+  fi
 
   yaimlog DEBUG "Configure the request scheduler"
-  if [ "x${VAR_VOMS_ADMIN_REQUEST_SCHEDULER}" == "xno" ]; then
+  value=`get_vo_param ${vo} VOMS_ADMIN_REQUEST_SCHEDULER`
+  if [ "x${value}" == "xno" ]; then
+    sched=no
+  else
+    if [ "x${value}" == "xyes" ]; then
+      sched=yes
+    else
+      if [ "x${VOMS_ADMIN_REQUEST_SCHEDULER}" == "xno" ]; then
+        sched=no
+      else 
+        if [ "x${VOMS_ADMIN_REQUEST_SCHEDULER}" == "xyes" ]; then
+          sched=yes
+        else
+          sched=no
+        fi
+      fi
+    fi
+  fi
+  if [ "x${sched}" == "xno" ]; then
     echo "voms.complete.requests.expire.after 0" >> ${GLITE_LOCATION_VAR}/etc/voms-admin/${vo}/voms.service.properties
     echo "voms.incomplete.requests.time.out.after 0" >> ${GLITE_LOCATION_VAR}/etc/voms-admin/${vo}/voms.service.properties
     echo "voms.request.expire.task.period.hours 0" >> ${GLITE_LOCATION_VAR}/etc/voms-admin/${vo}/voms.service.properties
